# Generated by Django 3.2 on 2021-05-29 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=40, verbose_name='Année')),
            ],
            options={
                'verbose_name': 'Année Académique',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name="Intitulé de le l'école/Institut/Faculté")),
            ],
            options={
                'verbose_name': 'Ecole/Institut/Faculté',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar/')),
                ('code_teacher', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Enseignant')),
                ('inscription_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Intitulé de la Filière')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.ecole', verbose_name='Ecole/Institut/Faculté')),
            ],
            options={
                'verbose_name': 'Filière',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=220, null=True, verbose_name='Thème du mémoire')),
                ('code_memoire', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Mémoire')),
                ('supervisor', models.CharField(blank=True, max_length=120, null=True, verbose_name='Superviseur')),
                ('middleClass', models.FloatField(blank=True, default=0, null=True, verbose_name='Note obtenue')),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('Assez-bien', 'Assez-bien'), ('Bien', 'Bien'), ('Très-bien', 'Très-bien'), ('Excellente', 'Excellente')], max_length=20, null=True, verbose_name='Mention')),
                ('activate', models.BooleanField(default=False, verbose_name='Memoire Active/Désactive')),
                ('stateBefore', models.BooleanField(default=False, verbose_name='Statut avant la Soutenance')),
                ('stateAfter', models.BooleanField(default=False, verbose_name='Statut après la soutenance')),
                ('depositDay', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Résumé du Mémoire')),
                ('presentationImage', models.ImageField(blank=True, null=True, upload_to='image_memoire/', verbose_name='Image de présentation')),
                ('document', models.FileField(upload_to='document_memoire/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Veuillez charger uniquement des documents de type pdf.')], verbose_name='Document du Mémoire')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('academicYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.academic_year', verbose_name='Année Académique')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Mémoire',
                'ordering': ['-depositDay'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Président du Jury'), (2, 'Vice-président du Jury'), (3, 'Membre du Jury')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name="Intitulé de l'Université")),
            ],
            options={
                'verbose_name': 'Université',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateTimeField(verbose_name='Date de soutenance')),
                ('jury_number', models.IntegerField(default=1, verbose_name='Numéro Jury')),
                ('place', models.CharField(default='', max_length=100, verbose_name='Lieu de la soutenance')),
                ('memoire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comptes.memoire', verbose_name='Mémoire')),
                ('teachers', models.ManyToManyField(through='comptes.Role', to='comptes.Enseignant', verbose_name='Enseignants assignés')),
            ],
            options={
                'verbose_name': 'Soutenance',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='soutenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.soutenance'),
        ),
        migrations.AddField(
            model_name='role',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.enseignant', verbose_name='Enseignant'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Option')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.ecole', verbose_name='Filière')),
            ],
            options={
                'ordering': ['ecole__name'],
            },
        ),
        migrations.AddField(
            model_name='memoire',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.option'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Prénom')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar/')),
                ('inscription_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
                ('memoire', models.ManyToManyField(blank=True, to='comptes.Memoire', verbose_name='Mémoires')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
        ),
        migrations.AddField(
            model_name='ecole',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.university', verbose_name='Université'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.memoire', verbose_name='Mémoire')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_agent', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Agent')),
                ('inscription_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.ecole', verbose_name='Ecole')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent du Secrétariat',
            },
        ),
    ]
