# Generated by Django 3.2 on 2021-05-30 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_auto_20210530_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.filiere', verbose_name='Filière'),
        ),
    ]
