# Generated by Django 3.2 on 2021-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_option_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Memoire Active/Désactive'),
        ),
    ]
