# Generated by Django 3.2 on 2021-06-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0004_alter_memoire_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='ecole',
            field=models.ManyToManyField(blank=True, null=True, to='comptes.Ecole'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
