# Generated by Django 3.2 on 2021-06-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_auto_20210607_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='code_teacher',
        ),
    ]
