# Generated by Django 3.2 on 2021-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_remove_enseignant_code_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='code_memoire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code Mémoire'),
        ),
    ]
