# Generated by Django 3.2 on 2021-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_memoire_code_memoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(1, 'Président du Jury'), (2, 'Vice-président du Jury'), (3, 'Membre du Jury')], default=3, unique=True),
        ),
    ]
