# Generated by Django 3.2 on 2021-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(1, 'Président du Jury'), (2, 'Membre du Jury')], default=2),
        ),
    ]
