# Generated by Django 3.2 on 2021-05-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0004_alter_memoire_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.academic_year', verbose_name='Année académique')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.ecole', verbose_name='Ecole')),
            ],
        ),
    ]
