# Generated by Django 3.2 on 2021-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloture',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de cloture de mémoire'),
        ),
    ]
