# Generated by Django 3.2 on 2021-06-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_auto_20210607_1901'),
        ('memoires', '0002_cloture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloture',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.academic_year', verbose_name='Annee academique'),
        ),
        migrations.AlterField(
            model_name='cloture',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de cloture des depots'),
        ),
    ]
